// <auto-generated />
using System;
using LinkMeetShareProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkMeetShareProject.Migrations
{
    [DbContext(typeof(LinkMeetShareProjectDbContext))]
    partial class LinkMeetShareProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("LinkMeetShareProject.Models.MeetingLink", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("MeetingLink", (string)null);
                });

            modelBuilder.Entity("LinkMeetShareProject.Models.MeetingLinkUser", b =>
                {
                    b.Property<int>("MeetingLinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeetingLinkId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetingLinkUser", (string)null);
                });

            modelBuilder.Entity("LinkMeetShareProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LinkMeetShareProject.Models.MeetingLinkUser", b =>
                {
                    b.HasOne("LinkMeetShareProject.Models.MeetingLink", "MeetingLink")
                        .WithMany("Users")
                        .HasForeignKey("MeetingLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkMeetShareProject.Models.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingLink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkMeetShareProject.Models.MeetingLink", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LinkMeetShareProject.Models.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
